apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: intelbo-ingress
spec:
  ingressClassName: avi-lb
  rules:
    - host: intelbo.tanzu.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: boapi
                port:
                  number: 80
          - path: /cbxqb
            pathType: Prefix
            backend:
              service:
                name: boui-k1-portal-ui-bo
                port:
                  number: 80