apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  ingressClassName: avi-lb
  rules:
    - host: intelbackofficebo.tanzu.lab
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: boapi
                port:
                  number: 80